apiVersion: v1
kind: Pod
metadata:
  name: port-forwarder
  namespace: video-host
spec:
  containers:
  - name: port-forwarder
    image: bitnami/kubectl:latest
    command: ["kubectl"]
    args: ["port-forward", "service/video-host-service", "3000:80", "--address=0.0.0.0"]
    ports:
    - containerPort: 3000
      hostPort: 3000