apiVersion: v1
kind: Service
metadata:
  name: video-host-service
  labels:
    app: video-host
spec:
  selector:
    app: video-host
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
  sessionAffinity: ClientIP